#' Simulated data for landmulti package
#'
#' This is a simulated data used as an example and test for \code{multipredict()} function. The data is
#' randomly generated by computer and has no practical meanning.
#'
#' @name simulation
#' @docType data
#' @usage data(simulation)
#'
#'
#' @keywords datasets
"simulation"
